spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: task-service
              uri: ${TASK_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/tasks/**

            - id: analytics-service
              uri: ${ANALYTICS_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/analytics/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:5173"
                  - "http://127.0.0.1:5173"
                  - "http://172.23.1.236:5173"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - "*"
                allow-credentials: true

server:
  port: ${SERVER_PORT:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always